export const GET_ORGANIZATION_LIST = 'GET_ORGANIZATION_LIST';
export const UPDATE_SELECTED_ORGANIZATION = 'UPDATE_SELECTED_ORGANIZATION';

export const GET_TEST_REPORT_LIST = 'GET_TEST_REPORT_LIST';
export const GET_TEST_REPORT_DETAIL = 'GET_TEST_REPORT_DETAIL';
export const FILTER_BY_SERVICE = 'FILTER_BY_SERVICE';